# see https://github.com/ELIXIR-Belgium/elixir-toolkit-theme
title: "How-to-Guides"
description: A collection of bioinformatics focused How-to-Guides
remote_theme: ELIXIR-Belgium/jekyll-bootstrap-theme@md-changes

theme_variables:
  # biocommons blue
  theme_color: 205a86
  topnav:
    brand_logo: assets/img/main_logo.png

permalink: /:categories/:year/:month/:day/:title

exclude:
  - README.md

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: main
