# see https://github.com/ELIXIR-Belgium/elixir-toolkit-theme
title: "How-to-Guides"
description: A collection of bioinformatics focused How-to-Guides
remote_theme: ELIXIR-Belgium/jekyll-bootstrap-theme@1.1.2

theme_variables:
  # biocommons blue
  theme_color: 205a86

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: main
